accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

daily_stack/urls.py
from django.urls import include,path
from . import views

app_name = "daily_stack"

urlpatterns = [

        path("", views.index, name="index"),
        path("<int:assignment_id>", views.assignment, name="assignment"),

        ]

accounts/models.py
from django.db import models

# Create your models here.

daily_stack/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Assignment(models.Model):

    due_date = models.DateField(auto_now=False,auto_now_add=False)
    assigned_date = models.DateField(auto_now_add=True)
    difficulty = models.PositiveIntegerField(default=2, validators=[MinValueValidator(1), MaxValueValidator(5)])
    name = models.CharField(max_length=100, default="essay")

    def __str__(self):
        return self.name

class Stack(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    assignments = models.ManyToManyField(Assignment)

    def remove_assignment(self, a):
        self.assignments.remove(a)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

daily_stack/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import *
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your views here.

class assignmentForm(forms.Form):
    name = forms.CharField(label="Assignment name")
    due_date = forms.DateField(label="Due date")
    difficulty = forms.IntegerField(label="Difficulty (1-5)", validators=[MinValueValidator(1), MaxValueValidator(5)])

#class removeForm(forms.Form):

def index(request):
    
    try:
        stack = Stack.objects.get(user=request.user.id)

    except Stack.DoesNotExist:
        print('stackless')

        stack = Stack(user=request.user.id)
        assignments = stack.assignments.all()
        return render(request, "daily_stack/index.html", {
            "stack":assignments,
            "form":assignmentForm(),
                })


    assignments = (stack.assignments.all())
    if request.method=="POST" and "remove_btn" not in request.POST:

        form = assignmentForm(request.POST)
        

        if form.is_valid():
            name = request.POST.get('name')
            due_date = request.POST.get('due_date')
            difficulty = request.POST.get('difficulty')

            a = Assignment(name=name,due_date=due_date,difficulty=difficulty)
            a.save()

         
            # don't repeat code. re-structure later.

            stack.assignments.add(a)
            stack.save()

            assignments = stack.assignments.all()
            
            return render(request, "daily_stack/index.html", {
                "form": assignmentForm(),
                "stack":assignments,
                })
        
        elif request.method=="POST" and "remove_btn" in request.POST:
            pass
            # do something

        else:
            return render(request, "daily_stack/index.html", {
                "form": assignmentForm(),
                "stack":assignments,
                })

    return render(request, "daily_stack/index.html", {
        "form": assignmentForm(),
        "stack":assignments,
        })

def assignment(request, assignment_id):
    
    assignment = Assignment.objects.get(pk=assignment_id)
    stack = Stack.objects.get(user=request.user.id)

    if request.method=="POST":
        print("posting")
        stack.remove_assignment(assignment)
        return redirect("daily_stack:index")

    
    return render(request, "daily_stack/assignment.html",{
        "assignment":assignment,
        })

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/daily_stack/assignment.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1> {{ assignment.name }}</h1>

 <p>{{ assignment.due_date }}</p>
 <p>{{ assignment.difficulty }}</p>


 <h2> Remove assignment? </h2>

 <form action "{% url 'daily_stack:assignment' assignment.id %}" method="post">
     {% csrf_token %}

     <button id="submit-button" name="remove_btn" type="submit" class="btn btn-primary">Remove Assignment</button>

 </form>



  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

templates/daily_stack/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1> {{ user.username }}'s Stack:</h1>

 {% for s in stack %}

 <a href="{% url 'daily_stack:assignment' s.id %}">
 <p>{{ s.name }}</p>
 </a>


 {% endfor %}

 <h2> Add a new assignment: </h2>

 <form action "{% url 'daily_stack:index' %}" method="post">
     {% csrf_token %}
     {{ form }}

     <button id="submit-button" type="submit" class="btn btn-primary">Submit</button>

 </form>



  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}